### ISSUE TITLE
Frontend can do better

### ISSUE THREAD

**Issue by ayushete02** [xmtp/xmtp-quickstart-react#10]
I think we need to update frontend

**Comment by jennifertrin** [comment]
@ayushete02 Can you please elaborate more on what updates you are looking for in the frontend?

**Comment by nplasterer** [comment]
@ayushete02 this is a simple example app. Do mind sharing more information on what you'd like to see updated?

**Comment by ayushete02** [comment]
The UI of the Chatting page should be updated

**Comment by nplasterer** [comment]
@ayushete02 since this is just a simple quickstart example I don't think we are going to invest any more time into updating the UI but if you want to see a more advanced implementation with better UI you can check out https://github.com/xmtp-labs/xmtp-inbox-web
