### ISSUE TITLE
TypeError: t.crypto.subtle is undefined

### ISSUE THREAD

**Issue by ngmisl** [xmtp/xmtp-quickstart-react#12]
just forked and installed, when I try to connect to xmtp I'm getting

`TypeError: t.crypto.subtle is undefined`

TypeError: t.crypto.subtle is undefined
    node_modules bundle.js:38918
    node_modules bundle.js:38900
    node_modules bundle.js:38879
    c index.js:2
    node_modules bundle.js:38951
    node_modules bundle.js:38900
    node_modules bundle.js:38879
    node_modules bundle.js:38949
    node_modules bundle.js:39371
    s index.js:2
    setTimeout handler*write/< inpage.js:1
    write inpage.js:1
    w inpage.js:17
    s inpage.js:17
    write inpage.js:17
    g inpage.js:17
    f inpage.js:8
    emit inpage.js:8
    _ inpage.js:17
    v inpage.js:17
    push inpage.js:17
    _write inpage.js:1
    w inpage.js:17
    s inpage.js:17
    write inpage.js:17
    g inpage.js:1
    f inpage.js:8
    emit inpage.js:8
    _ inpage.js:1
    v inpage.js:1
    push inpage.js:1
    _onData inpage.js:1
    _onMessage inpage.js:1
XmtpContext.js:30

**Comment by rygine** [comment]
@ngmisl This error is likely a result of [Crypto.subtle](https://developer.mozilla.org/en-US/docs/Web/API/Crypto/subtle) being unavailable in your environment. Please check the compatibility table in the linked documentation and confirm if your environment meets the requirements.
